version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push myregistry/myimage:latest
      - run: |
          ssh -o StrictHostKeyChecking=no myuser@myserver "docker pull myregistry/myimage:latest"
          ssh -o StrictHostKeyChecking=no myuser@myserver "docker-compose -f /path/to/docker-compose.yml up -d"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
