version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: docker-compose build
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run: docker-compose up -d
      - run: sleep 30
      - run: curl -I localhost:3000
      - run: docker-compose down

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
